/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RingSizeGuideRouteImport } from './routes/ring-size-guide'
import { Route as OccasionsRouteImport } from './routes/occasions'
import { Route as EducationRouteImport } from './routes/education'
import { Route as CustomOrderRouteImport } from './routes/custom-order'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BespokeRouteImport } from './routes/bespoke'
import { Route as AssuranceRouteImport } from './routes/assurance'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShapeShapeRouteImport } from './routes/shape.$shape'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as CollectionsCategoryRouteImport } from './routes/collections.$category'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RingSizeGuideRoute = RingSizeGuideRouteImport.update({
  id: '/ring-size-guide',
  path: '/ring-size-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const OccasionsRoute = OccasionsRouteImport.update({
  id: '/occasions',
  path: '/occasions',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomOrderRoute = CustomOrderRouteImport.update({
  id: '/custom-order',
  path: '/custom-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BespokeRoute = BespokeRouteImport.update({
  id: '/bespoke',
  path: '/bespoke',
  getParentRoute: () => rootRouteImport,
} as any)
const AssuranceRoute = AssuranceRouteImport.update({
  id: '/assurance',
  path: '/assurance',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShapeShapeRoute = ShapeShapeRouteImport.update({
  id: '/shape/$shape',
  path: '/shape/$shape',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCategoryRoute = CollectionsCategoryRouteImport.update({
  id: '/collections/$category',
  path: '/collections/$category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assurance': typeof AssuranceRoute
  '/bespoke': typeof BespokeRoute
  '/contact': typeof ContactRoute
  '/custom-order': typeof CustomOrderRoute
  '/education': typeof EducationRoute
  '/occasions': typeof OccasionsRoute
  '/ring-size-guide': typeof RingSizeGuideRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/collections/$category': typeof CollectionsCategoryRoute
  '/product/$slug': typeof ProductSlugRoute
  '/shape/$shape': typeof ShapeShapeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assurance': typeof AssuranceRoute
  '/bespoke': typeof BespokeRoute
  '/contact': typeof ContactRoute
  '/custom-order': typeof CustomOrderRoute
  '/education': typeof EducationRoute
  '/occasions': typeof OccasionsRoute
  '/ring-size-guide': typeof RingSizeGuideRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/collections/$category': typeof CollectionsCategoryRoute
  '/product/$slug': typeof ProductSlugRoute
  '/shape/$shape': typeof ShapeShapeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assurance': typeof AssuranceRoute
  '/bespoke': typeof BespokeRoute
  '/contact': typeof ContactRoute
  '/custom-order': typeof CustomOrderRoute
  '/education': typeof EducationRoute
  '/occasions': typeof OccasionsRoute
  '/ring-size-guide': typeof RingSizeGuideRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/collections/$category': typeof CollectionsCategoryRoute
  '/product/$slug': typeof ProductSlugRoute
  '/shape/$shape': typeof ShapeShapeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/assurance'
    | '/bespoke'
    | '/contact'
    | '/custom-order'
    | '/education'
    | '/occasions'
    | '/ring-size-guide'
    | '/sitemap.xml'
    | '/collections/$category'
    | '/product/$slug'
    | '/shape/$shape'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/assurance'
    | '/bespoke'
    | '/contact'
    | '/custom-order'
    | '/education'
    | '/occasions'
    | '/ring-size-guide'
    | '/sitemap.xml'
    | '/collections/$category'
    | '/product/$slug'
    | '/shape/$shape'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/assurance'
    | '/bespoke'
    | '/contact'
    | '/custom-order'
    | '/education'
    | '/occasions'
    | '/ring-size-guide'
    | '/sitemap.xml'
    | '/collections/$category'
    | '/product/$slug'
    | '/shape/$shape'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AssuranceRoute: typeof AssuranceRoute
  BespokeRoute: typeof BespokeRoute
  ContactRoute: typeof ContactRoute
  CustomOrderRoute: typeof CustomOrderRoute
  EducationRoute: typeof EducationRoute
  OccasionsRoute: typeof OccasionsRoute
  RingSizeGuideRoute: typeof RingSizeGuideRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CollectionsCategoryRoute: typeof CollectionsCategoryRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ShapeShapeRoute: typeof ShapeShapeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ring-size-guide': {
      id: '/ring-size-guide'
      path: '/ring-size-guide'
      fullPath: '/ring-size-guide'
      preLoaderRoute: typeof RingSizeGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/occasions': {
      id: '/occasions'
      path: '/occasions'
      fullPath: '/occasions'
      preLoaderRoute: typeof OccasionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-order': {
      id: '/custom-order'
      path: '/custom-order'
      fullPath: '/custom-order'
      preLoaderRoute: typeof CustomOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bespoke': {
      id: '/bespoke'
      path: '/bespoke'
      fullPath: '/bespoke'
      preLoaderRoute: typeof BespokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assurance': {
      id: '/assurance'
      path: '/assurance'
      fullPath: '/assurance'
      preLoaderRoute: typeof AssuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shape/$shape': {
      id: '/shape/$shape'
      path: '/shape/$shape'
      fullPath: '/shape/$shape'
      preLoaderRoute: typeof ShapeShapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$category': {
      id: '/collections/$category'
      path: '/collections/$category'
      fullPath: '/collections/$category'
      preLoaderRoute: typeof CollectionsCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AssuranceRoute: AssuranceRoute,
  BespokeRoute: BespokeRoute,
  ContactRoute: ContactRoute,
  CustomOrderRoute: CustomOrderRoute,
  EducationRoute: EducationRoute,
  OccasionsRoute: OccasionsRoute,
  RingSizeGuideRoute: RingSizeGuideRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CollectionsCategoryRoute: CollectionsCategoryRoute,
  ProductSlugRoute: ProductSlugRoute,
  ShapeShapeRoute: ShapeShapeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
