/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RingSizeGuideRouteImport } from './routes/ring-size-guide'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as OccasionsRouteImport } from './routes/occasions'
import { Route as GiftsRouteImport } from './routes/gifts'
import { Route as EducationRouteImport } from './routes/education'
import { Route as DiamondsRouteImport } from './routes/diamonds'
import { Route as CustomOrderRouteImport } from './routes/custom-order'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BespokeRouteImport } from './routes/bespoke'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssuranceRouteImport } from './routes/assurance'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShapeShapeRouteImport } from './routes/shape.$shape'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as OrderCodeRouteImport } from './routes/order.$code'
import { Route as CollectionsCategoryRouteImport } from './routes/collections.$category'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSeoRouteImport } from './routes/_authenticated/admin.seo'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin.products'
import { Route as AuthenticatedAdminPopupsRouteImport } from './routes/_authenticated/admin.popups'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin.orders'
import { Route as AuthenticatedAdminOffersRouteImport } from './routes/_authenticated/admin.offers'
import { Route as AuthenticatedAdminMenuRouteImport } from './routes/_authenticated/admin.menu'
import { Route as AuthenticatedAdminGiftsRouteImport } from './routes/_authenticated/admin.gifts'
import { Route as AuthenticatedAdminEnquiriesRouteImport } from './routes/_authenticated/admin.enquiries'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'
import { Route as AuthenticatedAdminAutomationsRouteImport } from './routes/_authenticated/admin.automations'
import { Route as AuthenticatedAdminOrdersIdLabelRouteImport } from './routes/_authenticated/admin.orders.$id.label'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RingSizeGuideRoute = RingSizeGuideRouteImport.update({
  id: '/ring-size-guide',
  path: '/ring-size-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const OccasionsRoute = OccasionsRouteImport.update({
  id: '/occasions',
  path: '/occasions',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftsRoute = GiftsRouteImport.update({
  id: '/gifts',
  path: '/gifts',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const DiamondsRoute = DiamondsRouteImport.update({
  id: '/diamonds',
  path: '/diamonds',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomOrderRoute = CustomOrderRouteImport.update({
  id: '/custom-order',
  path: '/custom-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BespokeRoute = BespokeRouteImport.update({
  id: '/bespoke',
  path: '/bespoke',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssuranceRoute = AssuranceRouteImport.update({
  id: '/assurance',
  path: '/assurance',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShapeShapeRoute = ShapeShapeRouteImport.update({
  id: '/shape/$shape',
  path: '/shape/$shape',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderCodeRoute = OrderCodeRouteImport.update({
  id: '/order/$code',
  path: '/order/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCategoryRoute = CollectionsCategoryRouteImport.update({
  id: '/collections/$category',
  path: '/collections/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSeoRoute = AuthenticatedAdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPopupsRoute =
  AuthenticatedAdminPopupsRouteImport.update({
    id: '/popups',
    path: '/popups',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOffersRoute =
  AuthenticatedAdminOffersRouteImport.update({
    id: '/offers',
    path: '/offers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMenuRoute = AuthenticatedAdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminGiftsRoute = AuthenticatedAdminGiftsRouteImport.update({
  id: '/gifts',
  path: '/gifts',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminEnquiriesRoute =
  AuthenticatedAdminEnquiriesRouteImport.update({
    id: '/enquiries',
    path: '/enquiries',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAutomationsRoute =
  AuthenticatedAdminAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersIdLabelRoute =
  AuthenticatedAdminOrdersIdLabelRouteImport.update({
    id: '/$id/label',
    path: '/$id/label',
    getParentRoute: () => AuthenticatedAdminOrdersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assurance': typeof AssuranceRoute
  '/auth': typeof AuthRoute
  '/bespoke': typeof BespokeRoute
  '/contact': typeof ContactRoute
  '/custom-order': typeof CustomOrderRoute
  '/diamonds': typeof DiamondsRoute
  '/education': typeof EducationRoute
  '/gifts': typeof GiftsRoute
  '/occasions': typeof OccasionsRoute
  '/offers': typeof OffersRoute
  '/ring-size-guide': typeof RingSizeGuideRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wishlist': typeof WishlistRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/collections/$category': typeof CollectionsCategoryRoute
  '/order/$code': typeof OrderCodeRoute
  '/product/$slug': typeof ProductSlugRoute
  '/shape/$shape': typeof ShapeShapeRoute
  '/admin/automations': typeof AuthenticatedAdminAutomationsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/admin/gifts': typeof AuthenticatedAdminGiftsRoute
  '/admin/menu': typeof AuthenticatedAdminMenuRoute
  '/admin/offers': typeof AuthenticatedAdminOffersRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRouteWithChildren
  '/admin/popups': typeof AuthenticatedAdminPopupsRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/orders/$id/label': typeof AuthenticatedAdminOrdersIdLabelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assurance': typeof AssuranceRoute
  '/auth': typeof AuthRoute
  '/bespoke': typeof BespokeRoute
  '/contact': typeof ContactRoute
  '/custom-order': typeof CustomOrderRoute
  '/diamonds': typeof DiamondsRoute
  '/education': typeof EducationRoute
  '/gifts': typeof GiftsRoute
  '/occasions': typeof OccasionsRoute
  '/offers': typeof OffersRoute
  '/ring-size-guide': typeof RingSizeGuideRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wishlist': typeof WishlistRoute
  '/collections/$category': typeof CollectionsCategoryRoute
  '/order/$code': typeof OrderCodeRoute
  '/product/$slug': typeof ProductSlugRoute
  '/shape/$shape': typeof ShapeShapeRoute
  '/admin/automations': typeof AuthenticatedAdminAutomationsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/admin/gifts': typeof AuthenticatedAdminGiftsRoute
  '/admin/menu': typeof AuthenticatedAdminMenuRoute
  '/admin/offers': typeof AuthenticatedAdminOffersRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRouteWithChildren
  '/admin/popups': typeof AuthenticatedAdminPopupsRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/orders/$id/label': typeof AuthenticatedAdminOrdersIdLabelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/assurance': typeof AssuranceRoute
  '/auth': typeof AuthRoute
  '/bespoke': typeof BespokeRoute
  '/contact': typeof ContactRoute
  '/custom-order': typeof CustomOrderRoute
  '/diamonds': typeof DiamondsRoute
  '/education': typeof EducationRoute
  '/gifts': typeof GiftsRoute
  '/occasions': typeof OccasionsRoute
  '/offers': typeof OffersRoute
  '/ring-size-guide': typeof RingSizeGuideRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wishlist': typeof WishlistRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/collections/$category': typeof CollectionsCategoryRoute
  '/order/$code': typeof OrderCodeRoute
  '/product/$slug': typeof ProductSlugRoute
  '/shape/$shape': typeof ShapeShapeRoute
  '/_authenticated/admin/automations': typeof AuthenticatedAdminAutomationsRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/_authenticated/admin/gifts': typeof AuthenticatedAdminGiftsRoute
  '/_authenticated/admin/menu': typeof AuthenticatedAdminMenuRoute
  '/_authenticated/admin/offers': typeof AuthenticatedAdminOffersRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRouteWithChildren
  '/_authenticated/admin/popups': typeof AuthenticatedAdminPopupsRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/orders/$id/label': typeof AuthenticatedAdminOrdersIdLabelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/assurance'
    | '/auth'
    | '/bespoke'
    | '/contact'
    | '/custom-order'
    | '/diamonds'
    | '/education'
    | '/gifts'
    | '/occasions'
    | '/offers'
    | '/ring-size-guide'
    | '/sitemap.xml'
    | '/wishlist'
    | '/admin'
    | '/collections/$category'
    | '/order/$code'
    | '/product/$slug'
    | '/shape/$shape'
    | '/admin/automations'
    | '/admin/categories'
    | '/admin/enquiries'
    | '/admin/gifts'
    | '/admin/menu'
    | '/admin/offers'
    | '/admin/orders'
    | '/admin/popups'
    | '/admin/products'
    | '/admin/seo'
    | '/admin/users'
    | '/admin/'
    | '/admin/orders/$id/label'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/assurance'
    | '/auth'
    | '/bespoke'
    | '/contact'
    | '/custom-order'
    | '/diamonds'
    | '/education'
    | '/gifts'
    | '/occasions'
    | '/offers'
    | '/ring-size-guide'
    | '/sitemap.xml'
    | '/wishlist'
    | '/collections/$category'
    | '/order/$code'
    | '/product/$slug'
    | '/shape/$shape'
    | '/admin/automations'
    | '/admin/categories'
    | '/admin/enquiries'
    | '/admin/gifts'
    | '/admin/menu'
    | '/admin/offers'
    | '/admin/orders'
    | '/admin/popups'
    | '/admin/products'
    | '/admin/seo'
    | '/admin/users'
    | '/admin'
    | '/admin/orders/$id/label'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/assurance'
    | '/auth'
    | '/bespoke'
    | '/contact'
    | '/custom-order'
    | '/diamonds'
    | '/education'
    | '/gifts'
    | '/occasions'
    | '/offers'
    | '/ring-size-guide'
    | '/sitemap.xml'
    | '/wishlist'
    | '/_authenticated/admin'
    | '/collections/$category'
    | '/order/$code'
    | '/product/$slug'
    | '/shape/$shape'
    | '/_authenticated/admin/automations'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/enquiries'
    | '/_authenticated/admin/gifts'
    | '/_authenticated/admin/menu'
    | '/_authenticated/admin/offers'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/popups'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/seo'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/orders/$id/label'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AssuranceRoute: typeof AssuranceRoute
  AuthRoute: typeof AuthRoute
  BespokeRoute: typeof BespokeRoute
  ContactRoute: typeof ContactRoute
  CustomOrderRoute: typeof CustomOrderRoute
  DiamondsRoute: typeof DiamondsRoute
  EducationRoute: typeof EducationRoute
  GiftsRoute: typeof GiftsRoute
  OccasionsRoute: typeof OccasionsRoute
  OffersRoute: typeof OffersRoute
  RingSizeGuideRoute: typeof RingSizeGuideRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WishlistRoute: typeof WishlistRoute
  CollectionsCategoryRoute: typeof CollectionsCategoryRoute
  OrderCodeRoute: typeof OrderCodeRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ShapeShapeRoute: typeof ShapeShapeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ring-size-guide': {
      id: '/ring-size-guide'
      path: '/ring-size-guide'
      fullPath: '/ring-size-guide'
      preLoaderRoute: typeof RingSizeGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/occasions': {
      id: '/occasions'
      path: '/occasions'
      fullPath: '/occasions'
      preLoaderRoute: typeof OccasionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifts': {
      id: '/gifts'
      path: '/gifts'
      fullPath: '/gifts'
      preLoaderRoute: typeof GiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diamonds': {
      id: '/diamonds'
      path: '/diamonds'
      fullPath: '/diamonds'
      preLoaderRoute: typeof DiamondsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-order': {
      id: '/custom-order'
      path: '/custom-order'
      fullPath: '/custom-order'
      preLoaderRoute: typeof CustomOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bespoke': {
      id: '/bespoke'
      path: '/bespoke'
      fullPath: '/bespoke'
      preLoaderRoute: typeof BespokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assurance': {
      id: '/assurance'
      path: '/assurance'
      fullPath: '/assurance'
      preLoaderRoute: typeof AssuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shape/$shape': {
      id: '/shape/$shape'
      path: '/shape/$shape'
      fullPath: '/shape/$shape'
      preLoaderRoute: typeof ShapeShapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$code': {
      id: '/order/$code'
      path: '/order/$code'
      fullPath: '/order/$code'
      preLoaderRoute: typeof OrderCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$category': {
      id: '/collections/$category'
      path: '/collections/$category'
      fullPath: '/collections/$category'
      preLoaderRoute: typeof CollectionsCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/seo': {
      id: '/_authenticated/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AuthenticatedAdminSeoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/popups': {
      id: '/_authenticated/admin/popups'
      path: '/popups'
      fullPath: '/admin/popups'
      preLoaderRoute: typeof AuthenticatedAdminPopupsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/offers': {
      id: '/_authenticated/admin/offers'
      path: '/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AuthenticatedAdminOffersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/menu': {
      id: '/_authenticated/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AuthenticatedAdminMenuRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/gifts': {
      id: '/_authenticated/admin/gifts'
      path: '/gifts'
      fullPath: '/admin/gifts'
      preLoaderRoute: typeof AuthenticatedAdminGiftsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/enquiries': {
      id: '/_authenticated/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AuthenticatedAdminEnquiriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/automations': {
      id: '/_authenticated/admin/automations'
      path: '/automations'
      fullPath: '/admin/automations'
      preLoaderRoute: typeof AuthenticatedAdminAutomationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders/$id/label': {
      id: '/_authenticated/admin/orders/$id/label'
      path: '/$id/label'
      fullPath: '/admin/orders/$id/label'
      preLoaderRoute: typeof AuthenticatedAdminOrdersIdLabelRouteImport
      parentRoute: typeof AuthenticatedAdminOrdersRoute
    }
  }
}

interface AuthenticatedAdminOrdersRouteChildren {
  AuthenticatedAdminOrdersIdLabelRoute: typeof AuthenticatedAdminOrdersIdLabelRoute
}

const AuthenticatedAdminOrdersRouteChildren: AuthenticatedAdminOrdersRouteChildren =
  {
    AuthenticatedAdminOrdersIdLabelRoute: AuthenticatedAdminOrdersIdLabelRoute,
  }

const AuthenticatedAdminOrdersRouteWithChildren =
  AuthenticatedAdminOrdersRoute._addFileChildren(
    AuthenticatedAdminOrdersRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAutomationsRoute: typeof AuthenticatedAdminAutomationsRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminEnquiriesRoute: typeof AuthenticatedAdminEnquiriesRoute
  AuthenticatedAdminGiftsRoute: typeof AuthenticatedAdminGiftsRoute
  AuthenticatedAdminMenuRoute: typeof AuthenticatedAdminMenuRoute
  AuthenticatedAdminOffersRoute: typeof AuthenticatedAdminOffersRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRouteWithChildren
  AuthenticatedAdminPopupsRoute: typeof AuthenticatedAdminPopupsRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminSeoRoute: typeof AuthenticatedAdminSeoRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAutomationsRoute: AuthenticatedAdminAutomationsRoute,
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminEnquiriesRoute: AuthenticatedAdminEnquiriesRoute,
  AuthenticatedAdminGiftsRoute: AuthenticatedAdminGiftsRoute,
  AuthenticatedAdminMenuRoute: AuthenticatedAdminMenuRoute,
  AuthenticatedAdminOffersRoute: AuthenticatedAdminOffersRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRouteWithChildren,
  AuthenticatedAdminPopupsRoute: AuthenticatedAdminPopupsRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminSeoRoute: AuthenticatedAdminSeoRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AssuranceRoute: AssuranceRoute,
  AuthRoute: AuthRoute,
  BespokeRoute: BespokeRoute,
  ContactRoute: ContactRoute,
  CustomOrderRoute: CustomOrderRoute,
  DiamondsRoute: DiamondsRoute,
  EducationRoute: EducationRoute,
  GiftsRoute: GiftsRoute,
  OccasionsRoute: OccasionsRoute,
  OffersRoute: OffersRoute,
  RingSizeGuideRoute: RingSizeGuideRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WishlistRoute: WishlistRoute,
  CollectionsCategoryRoute: CollectionsCategoryRoute,
  OrderCodeRoute: OrderCodeRoute,
  ProductSlugRoute: ProductSlugRoute,
  ShapeShapeRoute: ShapeShapeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
